mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('photo-gallery/', include('photo_gallery.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/photo_gallery/urls.py
from django.urls import path

from photo_gallery.views import add_album_view, gallery_view

app_name = 'photo_gallery'
urlpatterns = [
    path('<str:album_name>/', gallery_view, name="gallery"),
    path('', add_album_view, name="index"),
]

mysite/portal/urls.py
from django.urls import path

from portal.views import portal_index

app_name = 'portal'
urlpatterns = [
    path('', portal_index, name="index"),
]

mysite/photo_gallery/models.py
from django.db import models


class Album(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return str(self.name)


def upload_gallery_image(instance, filename):
    return f"images/{instance.album.name}/gallery/{filename}"


class Image(models.Model):
    image = models.ImageField(upload_to=upload_gallery_image)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name="images")

mysite/portal/models.py
from django.db import models

# Create your models here.

mysite/photo_gallery/forms.py
from django import forms
from photo_gallery.models import Album, Image


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ("name",)


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ("image",)

mysite/photo_gallery/views.py
from django.shortcuts import render, redirect
from django.forms import modelformset_factory

from photo_gallery.models import Album, Image
from photo_gallery.forms import ImageForm, AlbumForm


def add_album_view(request):
    image_formset = modelformset_factory(Image, form=ImageForm, extra=3)

    if request.method == "GET":
        albums = Album.objects.all()
        album_form = AlbumForm()
        formset = image_formset(queryset=Image.objects.none())
        context = {"albums": albums, "album_form": album_form, "formset": formset}

        return render(request, "photo_gallery/index.html", context)

    album_form = AlbumForm(request.POST)
    formset = image_formset(request.POST, request.FILES)

    if album_form.is_valid() and formset.is_valid():
        album_obj = album_form.save()

        for form in formset.cleaned_data:
            if form:
                image = form["image"]
                Image.objects.create(image=image, album=album_obj)

        return redirect("index")

    print(album_form.errors, formset.errors)


def gallery_view(request, album_name):
    album = Album.objects.get(name=album_name)
    context = {"album": album}

    return render(request, "photo_gallery/gallery.html", context)

mysite/portal/views.py
from django.shortcuts import render

def portal_index(request):
    return render(request, "portal/index.html")

mysite/photo_gallery/templates/photo_gallery/gallery.html
{% extends "base_generic.html" %}
{% load static %}

{% block title %}Gallery | {% endblock title %}

{% block head_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'photo_gallery/main.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/2.7.0/simple-lightbox.css" integrity="sha512-8WAX0xL/cHZ38RXoX2gtuqkAwmDVAzGwoFVmHvn46IDHGWOjTHx0vcl9OapNrfOzpFtql0SNkv+0y0b5Fm8ZkA==" crossorigin="anonymous" />
{% endblock head_links %}

{% block header %}
    <h1>{{ album|capfirst }} gallery</h1>
{% endblock header %}

{% block content %}
    <div class="container">
        <section class="photo_gallery">
            {% for gallery_image in album.images.all %}
                <a href="{{ gallery_image.image.url }}"><img src="{{ gallery_image.image.url }}" alt="" title="" /></a>
            {% endfor %}
        </section>
    </div>
{% endblock content %}

{% block footer_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/2.7.0/simple-lightbox.min.js" integrity="sha512-ZajFBgnksNp8Rj+AbmYe8ueOu45HiSjtf3QpqnRbHlq719m6VK0FkbYIqQ8wEnlVuJ1i9pC+z6Z9ewmDnUTMCg==" crossorigin="anonymous"></script>
    <script>
        var gallery = new SimpleLightbox('.photo_gallery a');
    </script>
{% endblock footer_js %}

mysite/photo_gallery/templates/photo_gallery/index.html
{% extends "base_generic.html" %}
{% load static %}

{% block title %}Photo gallery | {% endblock title %}

{% block header %}
    <h1>Photo gallery</h1>
{% endblock header %}

{% block content %}
    <h2>Show album</h2>
    {% for album in albums %}
        <a href="{% url 'photo_gallery:gallery' album %}">{{ album }}</a>
    {% endfor %}
    <h2>Add album</h2>
    <form id="album_form" method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ album_form }}
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.as_p }}
        {% endfor %}
        <input type="submit" name="submit" value="Submit" />
    </form>
{% endblock content %}

mysite/portal/templates/portal/index.html
{% extends 'base_generic.html' %}
{% load static %}

mysite/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock title %}My site</title>
        {% block head_favicon %}
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_links %}
        {% endblock head_links %}
    </head>
    <body>
        <header>
            <div class="header">
                {% block header %}
                    <h1>My site</h1>
                {% endblock header %}
                <a href="{% url 'portal:index' %}">Home</a>
                <a href="{% url 'photo_gallery:index' %}">Photo gallery</a>
                <a href="{% url 'polls:index' %}">Polls</a>
                <a href="{% url 'admin:index' %}">Admin</a>
            </div>
        </header>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="footer">
            {% block footer %}
                <p>Simón Golpe Varela 2021-current</p>
            {% endblock footer %}
        </div>
    </body>
    {% block footer_js %}
    {% endblock footer_js %}
</html>

mysite/templates/polls/detail.html
{% extends "polls/index.html" %}
{% load static %}

{% block title %}{{ question.question_text|capfirst }} | {{ block.super }}{% endblock title %}

{% block header %}
    <h1>Vote poll "{{ question.question_text }}"</h1>
{% endblock header %}

{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
{% endblock content %}

mysite/templates/polls/index.html
{% extends "base_generic.html" %}
{% load static %}

{% block title %}Polls | {% endblock title %}

{% block head_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% endblock head_links %}

{% block header %}
    <h1>Polls</h1>
{% endblock header %}

{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}" >{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}

mysite/templates/polls/results.html
{% extends "polls/index.html" %}
{% load static %}

{% block title %}Result | {{ block.super }}{% endblock title %}

{% block header %}
    <h1>Results of poll "{{ question.question_text }}"</h1>
{% endblock header %}

{% block content %}
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}